<a href="https://colab.research.google.com/github/tbahng/MAR653-FinalProject/blob/jason/final_project/explore_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploration of Data Sources
* listings.csv.gz - Detailed listings data for New York City
* listings.csv - Summary information and metrics for listings in New York City
* calendar.csv.gz - Detailed calendar data for listings in New York City
* reviews.csv.gz - Detailed review data for listings in New York City
* reviews.csv - Summary review data and listing ID
* neighbourhoods.csv - Neighbourhood list for geo filter. Sourced from city or open source GIS files
* neighbourhoods.geojson - GeoJSON file of neighbourhoods of the city

For the purposes of this notebook, each file will be explored separately.

In [0]:
import pandas as pd 
import json
import os

# function to summarize data
# param: df dataframe
# print number of variables, data type counts, and variable names
def summarizeData(df):
    print("Number of Variables: {:d}\n".format(df.shape[1]))
    print("Number of Observations: {:d}\n".format(df.shape[0]))
    print("Data types:")
    print(df.dtypes.value_counts())    
    print("\nColumn Names by Type:\n")
    g = df.columns.to_series().groupby(df.dtypes).groups
    for item in g.items():
        print(item)

### Load Data Sources

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import pandas as pd

file_path = '/content/drive/My Drive/MAR 653/Final Project/data/{}'

calendar_df = pd.read_csv(file_path.format('calendar.csv.gz'), compression='gzip')
listings_summary_df = pd.read_csv(file_path.format('listings.csv'))
listings_detail_df = pd.read_csv(file_path.format('listings.csv.gz'), compression='gzip')
neighbourhoods_df = pd.read_csv(file_path.format('neighbourhoods.csv'))
neighbourhoods_geo_df = pd.read_json(file_path.format('neighbourhoods.geojson'))
reviews_summary_df = pd.read_csv(file_path.format('reviews.csv'))
reviews_detail_df = pd.read_csv(file_path.format('reviews.csv.gz'), compression='gzip')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
os.listdir('drive/My Drive/MAR 653/Final Project/data')

['calendar.csv.gz',
 'listings.csv.gz',
 'reviews.csv.gz',
 'listings_detailed',
 'reviews_detailed',
 'calendar_detailed',
 'neighbourhoods.csv',
 'neighbourhoods.geojson',
 'listings.csv',
 'reviews.csv',
 'prizm_attributes.xlsx',
 'listings_cleaned.csv',
 'listings_201512.csv',
 'listings_201612.csv',
 'listings_201712.csv',
 'listings_201812.csv',
 'listings_201912.csv']

In [0]:
# read geojson into dictionary
import json
with open('drive/My Drive/MAR 653/Final Project/data/neighbourhoods.geojson', 'r') as fin:
  geo = json.loads(fin.read())

## File: listings.csv.gz (detailed)
* Detailed Listings data for New York City
* Contains 50599 observations of 43 numeric and 63 object variables

In [6]:
listings_detail_df.describe()

id  ...  reviews_per_month
count  5.059900e+04  ...       40379.000000
mean   2.137380e+07  ...           1.405862
std    1.242864e+07  ...           1.695551
min    2.595000e+03  ...           0.010000
25%    1.009891e+07  ...           0.190000
50%    2.154642e+07  ...           0.740000
75%    3.271780e+07  ...           2.110000
max    4.058402e+07  ...          52.630000

[8 rows x 43 columns]

In [7]:
summarizeData(listings_detail_df)

Number of Variables: 106

Number of Observations: 50599

Data types:
object     63
float64    22
int64      21
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['id', 'scrape_id', 'host_id', 'accommodates', 'guests_included',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms'],
      dtype='object'))
(dtype('float64'), Index(['thumbnail_url', 'medium_url', 'xl_picture_url', 'host_acceptance_rate',
       'host_listings_count', 'host_total_listings_count', 'latitude',
       'longitude', 'bathrooms', 'bedrooms', 'beds', 'square_feet',
      

### Sample Observation

In [0]:
listings_detail_df.head()

id  ... reviews_per_month
0  2595  ...              0.39
1  3831  ...              4.67
2  5099  ...              0.60
3  5121  ...              0.38
4  5178  ...              3.52

[5 rows x 106 columns]

## File: listings.csv (summary)
* Summary information and metrics for listings in New York City (good for visualizations)
* Contains 50599 observations of 10 numeric and 6 object variables

In [0]:
listings_summary_df.describe()

id  ...  availability_365
count  5.059900e+04  ...      50599.000000
mean   2.137380e+07  ...        112.785944
std    1.242864e+07  ...        135.891028
min    2.595000e+03  ...          0.000000
25%    1.009891e+07  ...          0.000000
50%    2.154642e+07  ...         42.000000
75%    3.271780e+07  ...        225.000000
max    4.058402e+07  ...        365.000000

[8 rows x 10 columns]

In [0]:
summarizeData(listings_summary_df)

Number of Variables: 16

Number of Observations: 50599

Data types:
int64      7
object     6
float64    3
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['id', 'host_id', 'price', 'minimum_nights', 'number_of_reviews',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object'))
(dtype('float64'), Index(['latitude', 'longitude', 'reviews_per_month'], dtype='object'))
(dtype('O'), Index(['name', 'host_name', 'neighbourhood_group', 'neighbourhood',
       'room_type', 'last_review'],
      dtype='object'))


### Sample Observation

In [0]:
listings_summary_df.head()

id  ... availability_365
0  2595  ...                1
1  3831  ...                1
2  5099  ...               19
3  5121  ...              365
4  5178  ...              242

[5 rows x 16 columns]

## File: reviews.csv.gz (detailed)
* Detailed Review Data for listings in New York City
* Contains 1255322 observations of 3 numeric and 3 object variables

In [0]:
reviews_detail_df.describe()

listing_id            id   reviewer_id
count  1.255322e+06  1.255322e+06  1.255322e+06
mean   1.396211e+07  2.918422e+08  8.324934e+07
std    1.076478e+07  1.734486e+08  7.820263e+07
min    2.595000e+03  9.030000e+02  1.000000e+00
25%    4.081800e+06  1.415657e+08  1.876831e+07
50%    1.315684e+07  2.900042e+08  5.592106e+07
75%    2.173354e+07  4.526637e+08  1.324934e+08
max    4.056566e+07  5.736112e+08  3.146917e+08

In [0]:
summarizeData(reviews_detail_df)

Number of Variables: 6

Number of Observations: 1255322

Data types:
object    3
int64     3
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id', 'id', 'reviewer_id'], dtype='object'))
(dtype('O'), Index(['date', 'reviewer_name', 'comments'], dtype='object'))


### Sample Observation

In [8]:
reviews_detail_df.head()

listing_id  ...                                           comments
0        2595  ...  Notre séjour de trois nuits.\r\nNous avons app...
1        2595  ...                                  Great experience.
2        2595  ...  I've stayed with my friend at the Midtown Cast...
3        2595  ...  We've been staying here for about 9 nights, en...
4        2595  ...  We had a wonderful stay at Jennifer's charming...

[5 rows x 6 columns]

## File: reviews.csv (summary)
* Summary Review data and Listing ID (to facilitate time based analytics and visualizations linked to a listing)
* Contains 1255322 observations of 1 numeric and 1 object variables
* These are observations of review dates by listing ID.

In [0]:
reviews_summary_df.describe()

listing_id
count  1.255322e+06
mean   1.396211e+07
std    1.076478e+07
min    2.595000e+03
25%    4.081800e+06
50%    1.315684e+07
75%    2.173354e+07
max    4.056566e+07

In [0]:
summarizeData(reviews_summary_df)

Number of Variables: 2

Number of Observations: 1255322

Data types:
object    1
int64     1
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id'], dtype='object'))
(dtype('O'), Index(['date'], dtype='object'))


### Sample Observation

In [0]:
reviews_summary_df.head()

listing_id        date
0        2595  2009-11-21
1        2595  2009-12-05
2        2595  2009-12-10
3        2595  2010-04-09
4        2595  2010-05-25

## File: calendar.csv.gz (detailed)
> Detailed Calendar Data for listings in New York City

In [0]:
calendar_df.describe()

listing_id  minimum_nights  maximum_nights
count  1.847016e+07    1.846950e+07    1.846950e+07
mean   2.137365e+07    8.528041e+00    6.886948e+05
std    1.242861e+07    3.029394e+01    3.841186e+07
min    2.595000e+03    1.000000e+00    1.000000e+00
25%    1.009889e+07    1.000000e+00    2.900000e+01
50%    2.154642e+07    3.000000e+00    1.125000e+03
75%    3.271789e+07    5.000000e+00    1.125000e+03
max    4.058402e+07    3.456000e+03    2.147484e+09

In [0]:
summarizeData(calendar_df)

Number of Variables: 7

Number of Observations: 18470156

Data types:
object     4
float64    2
int64      1
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id'], dtype='object'))
(dtype('float64'), Index(['minimum_nights', 'maximum_nights'], dtype='object'))
(dtype('O'), Index(['date', 'available', 'price', 'adjusted_price'], dtype='object'))


### Sample Observation

In [0]:
calendar_df.head()

listing_id        date  ... minimum_nights maximum_nights
0       19812  2019-12-05  ...            3.0           90.0
1        2595  2019-12-06  ...           10.0         1125.0
2        2595  2019-12-07  ...           10.0         1125.0
3        2595  2019-12-08  ...           10.0         1125.0
4        2595  2019-12-09  ...           10.0         1125.0

[5 rows x 7 columns]

## File: neighbourhoods.csv
> Neighbourhood list for geo filter. Sourced from city or open source GIS files.

In [9]:
neighbourhoods_df.describe()

neighbourhood_group   neighbourhood
count                  230             230
unique                   5             230
top                 Queens  Pelham Gardens
freq                    53               1

In [0]:
summarizeData(neighbourhoods_df)

Number of Variables: 2

Number of Observations: 230

Data types:
object    2
dtype: int64

Column Names by Type:

(dtype('O'), Index(['neighbourhood_group', 'neighbourhood'], dtype='object'))


### Sample Observation

In [0]:
neighbourhoods_df.head()

neighbourhood_group neighbourhood
0               Bronx      Allerton
1               Bronx    Baychester
2               Bronx       Belmont
3               Bronx     Bronxdale
4               Bronx   Castle Hill

## File: neighbourhoods.geojson
> GeoJSON file of neighbourhoods of the city

In [0]:
geo.keys()

dict_keys(['type', 'features'])

In [0]:
geo['type']

'FeatureCollection'

In [0]:
print("There are {:d} feature sets in the collection".format(len(geo['features'])))

There are 233 feature sets in the collection


### Sample Observation

In [0]:
# inspect first feature set
geo['features'][0]

{'geometry': {'coordinates': [[[[-73.766708, 40.614911],
     [-73.768253, 40.614878],
     [-73.773977, 40.616004],
     [-73.773631, 40.616327],
     [-73.768735, 40.620901],
     [-73.767459, 40.620511],
     [-73.766978, 40.616919],
     [-73.766708, 40.614911]]]],
  'type': 'MultiPolygon'},
 'properties': {'neighbourhood': 'Bayswater', 'neighbourhood_group': 'Queens'},
 'type': 'Feature'}

Each feature set contains latitude and longitude coordinates specific to neighbourhood and neighbourhood group.

In [0]:
# all neighbourhood groups
neighbourhoodgroups = set([f['properties']['neighbourhood_group'] for f in geo['features']])
print(neighbourhoodgroups)

{'Manhattan', 'Brooklyn', 'Bronx', 'Staten Island', 'Queens'}


In [0]:
# all neighbourhoods by neighbourhood group
for group in neighbourhoodgroups:
    # neighbourhoods respective to neighbourhood group
    nnames = [f['properties']['neighbourhood'] for f in geo['features'] if f['properties']['neighbourhood_group'] == group]
    print('\n',"group:",group)
    print(" neighbourhoods:{:d}".format(len(nnames)),'\n')
    print(nnames)


 group: Manhattan
 neighbourhoods:32 

['Battery Park City', 'Chinatown', 'Chelsea', 'Civic Center', 'East Harlem', 'East Village', 'Financial District', 'Flatiron District', 'Gramercy', 'Greenwich Village', 'Harlem', "Hell's Kitchen", 'Inwood', 'Kips Bay', 'Little Italy', 'Murray Hill', 'Lower East Side', 'Marble Hill', 'Midtown', 'Morningside Heights', 'NoHo', 'Nolita', 'SoHo', 'Roosevelt Island', 'Stuyvesant Town', 'Theater District', 'Tribeca', 'Two Bridges', 'Upper East Side', 'Upper West Side', 'Washington Heights', 'West Village']

 group: Brooklyn
 neighbourhoods:48 

['Bay Ridge', 'Gerritsen Beach', 'Bath Beach', 'Bedford-Stuyvesant', 'Bensonhurst', 'Bergen Beach', 'Boerum Hill', 'Borough Park', 'Brighton Beach', 'Prospect-Lefferts Gardens', 'Brooklyn Heights', 'Brownsville', 'Bushwick', 'Cypress Hills', 'Canarsie', 'Carroll Gardens', 'Clinton Hill', 'Cobble Hill', 'Crown Heights', 'Columbia St', 'Coney Island', 'DUMBO', 'Downtown Brooklyn', 'Dyker Heights', 'East Flatbush', 

# How neighborhood affects rental price?



In [13]:
listings_summary_df.head()

id  ... availability_365
0  2595  ...                1
1  3831  ...                1
2  5099  ...               19
3  5121  ...              365
4  5178  ...              242

[5 rows x 16 columns]

In [50]:
listings_neighbourhood_df = listings_summary_df[['price','neighbourhood','neighbourhood_group']]
listings_neighbourhood_df.head()

price       neighbourhood neighbourhood_group
0    225             Midtown           Manhattan
1     89        Clinton Hill            Brooklyn
2    200         Murray Hill           Manhattan
3     60  Bedford-Stuyvesant            Brooklyn
4     79      Hell's Kitchen           Manhattan

In [65]:
#from pandas import factorize
listings_neighbourhood_df['neighbourhood_factor'] = listings_neighbourhood_df['neighbourhood'].factorize()[0]
#listings_neighbourhood_df['neighbourhood'].factorize()[0]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [67]:
listings_neighbourhood_df['neighbourhood_group_factor'] = listings_neighbourhood_df['neighbourhood_group'].factorize()[0]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
from sklearn import linear_model

x = listings_neighbourhood_df[['price']]
y = listings_neighbourhood_df[['neighbourhood_factor', 'neighbourhood_group_factor']]

lm = linear_model.LinearRegression()
model = lm.fit(x,y)

chi square test
anova analysis variance test

In [72]:
model.summary()

AttributeError: ignored